# Generated by Django 6.0 on 2026-01-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("gamer", "Gamer"),
                ],
                default="gamer",
                max_length=20,
            ),
        ),
    ]
