# Generated by Django 6.0 on 2026-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0002_tenant_status"),
        ("users", "0004_user_is_verified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["tenant", "role"], name="idx_user_tenant_role"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_verified"], name="idx_user_email_verified"
            ),
        ),
    ]
