# Generated by Django 6.0 on 2026-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_tenant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("premium", "Premium"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
