# Generated by Django 6.0 on 2026-01-21 13:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_alter_genre_name_alter_platform_name"),
        ("tenants", "0002_tenant_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_games",
                        to="catalog.game",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_games",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_games",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant", "game"),
                        name="unique_active_tenant_game",
                    )
                ],
            },
        ),
    ]
