# Generated by Django 6.0 on 2026-01-16 06:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wishlist", "Wishlist"),
                            ("playing", "Playing"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="wishlist",
                        max_length=20,
                    ),
                ),
                ("hours_played", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "personal_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_games",
                        to="catalog.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_games",
                        to="catalog.platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserGameNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField()),
                (
                    "user_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="user_games.usergame",
                    ),
                ),
            ],
            options={
                "db_table": "user_game_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usergame",
            index=models.Index(
                fields=["user", "status"], name="user_games_user_id_9ea5ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergame",
            index=models.Index(
                fields=["created_at"], name="user_games_created_75d80c_idx"
            ),
        ),
    ]
