# Generated by Django 6.0 on 2026-01-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("user_games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergame",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_games",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usergamenote",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
    ]
