# Generated by Django 6.0 on 2026-01-21 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_genre_name_alter_platform_name"),
        ("tenant_games", "0001_initial"),
        ("tenants", "0002_tenant_status"),
        ("user_games", "0002_usergame_tenant_usergamenote_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergame",
            name="game",
        ),
        migrations.AddField(
            model_name="usergame",
            name="tenant_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant_games.tenantgame",
            ),
        ),
        migrations.AddIndex(
            model_name="usergame",
            index=models.Index(
                fields=["user", "tenant"], name="user_games_user_id_d81271_idx"
            ),
        ),
    ]
