# Generated by Django 6.0 on 2026-01-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_games", "0001_initial"),
        ("user_games", "0003_remove_usergame_game_usergame_tenant_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergame",
            name="tenant_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant_games.tenantgame",
            ),
        ),
    ]
