# Generated by Django 6.0 on 2026-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="hours_played",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
